#!/bin/bash -f
# ****************************************************************************
# Vivado (TM) v2018.2 (64-bit)
#
# Filename    : simulate.sh
# Simulator   : Xilinx Vivado Simulator
# Description : Script for simulating the design by launching the simulator
#
# Generated by Vivado on Tue Jan 08 08:35:17 GMT 2019
# SW Build 2258646 on Thu Jun 14 20:02:38 MDT 2018
#
# Copyright 1986-2018 Xilinx, Inc. All Rights Reserved.
#
# usage: simulate.sh
#
# ****************************************************************************
ExecStep()
{
"$@"
RETVAL=$?
if [ $RETVAL -ne 0 ]
then
exit $RETVAL
fi
}
ExecStep xsim axi_verifier_testbench_behav -key {Behavioral:sim_1:Functional:axi_verifier_testbench} -tclbatch axi_verifier_testbench.tcl -view /home/jonathanrainer/Documents/PhD/Kuuga/wcfg/axi_verifier_config.wcfg -log simulate.log
